### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by w8r** [patrickarlt/leaflet-virtual-grid#3]
Do you consider publishing that as a module? I would like to re-use this part of `FeatureLayer` to work with `OGC` services.

**Comment by patrickarlt** [comment]
@w8r sorry it took me so long. I definitely want to publish this as a module but I also want to get the testing and release structure setup. Look for a 0.1.0 for Leaflet 0.7.x and a 1.0.0 for Leaflet 1.0.0 sometime in the next week.

**Comment by patrickarlt** [comment]
@w8r This is published on NPM now. Use 0.1.1 for Leaflet 0.7 and 1.0.0 for Leaflet 1.0 betas.

**Comment by w8r** [comment]
@patrickarlt Thanks!
